# Site settings
title: Kevin Chiang
header-img: img/home-bg.jpg
email: kevinwchiang@gmail.com
description: "The development of a student learning about Full Stack Javascript Development"
baseurl: ""
url: "kevinwchiang.github.io"
twitter_username: 
github_username:  kevinwchiang
facebook_username: 

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
